# POST https://https://quiet-crag-45664.herokuapp.com/api/persons
POST https://https://quiet-crag-45664.herokuapp.com/api/persons
content-type: application/json

{
    "name": "mika",
    "number": "666"
}